version: '3.8'

services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: 'weather'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - defaultapp
    restart: always

  weatherservice:
    image: test:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/weather
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - defaultapp
    ports:
      - "8080:8080"

volumes:
  db_data:

networks:
  defaultapp:
    name: defaultapp
    driver: bridge